# Generated by Django 4.1 on 2022-08-26 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BR', 'Bronz'), ('GD', 'Gold'), ('PL', 'Platinum'), ('PP', 'Platinum Plus'), ('FR', 'Bedavaci')], default='FR', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='izinler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
