# Generated by Django 4.1 on 2022-08-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_icerik'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='yayinla',
            field=models.BooleanField(default=False),
        ),
    ]
