# Generated by Django 4.1 on 2022-08-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_yayinla'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='blog_resim/'),
        ),
    ]
