# Generated by Django 4.1 on 2022-08-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resim',
            field=models.ImageField(default='no-pic.jpg', upload_to='blog_resim/'),
        ),
    ]
