# Generated by Django 4.1 on 2022-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resim',
            field=models.ImageField(upload_to='blog_resim/'),
        ),
    ]
