# Generated by Django 4.1 on 2022-08-26 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuzdan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_birimi', models.CharField(choices=[('USD', 'Dolar'), ('EUR', 'Euro'), ('TL', 'Turk Lirasi'), ('BTC', 'Bitcoin')], default='TL', max_length=3)),
                ('bakiye', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuzdan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
